### ISSUE TITLE
Lodash is included in browser output

### ISSUE THREAD

**Issue by NicholasBoll** [autoric/scheming#24]
The project has a bower dependency on lodash, but also includes lodash with the output. Using something like [bower-main-files](https://github.com/ck86/main-bower-files) means lodash will get included more than once.

This takes the minified output from 18K (without lodash) to 70K. That is a significant amount extra to send to a browser (especially mobile). The build should not include lodash in the output and have a bower dependency as it does now.

**Comment by autoric** [comment]
Browserify pulls everything in and makes a standalone file. I'll look at my options.

**Comment by autoric** [comment]
Fixed in https://github.com/autoric/scheming/commit/d17825a8d120dfd498a0625117cd8abfef66770c
