### ISSUE TITLE
uuid not _exactly_ correct

### ISSUE THREAD

**Issue by FrankHassanabad** [autoric/scheming#8]
The UUID's are not exactly correct.  

From wikipedia:
http://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29

`
Version 4 UUIDs have the form xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx where x is any hexadecimal digit and y is one of 8, 9, A, or B (e.g., f47ac10b-58cc-4372-a567-0e02b2c3d479).
`

However, when running the uuid method several times it will return _more letters_ than 8, 9, A, or B for the "y" value.

The line here:

`((if c is "x" then r else (r & 0x7 | 0x8))).toString 16`
https://github.com/autoric/scheming/blob/master/src/Scheming.coffee#L20

should have the 0x7 replaced with 0x3 

like so

`((if c is "x" then r else (r & 0x3 | 0x8))).toString 16`

I got that from what looks like very similar code from:
http://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript

I think this was a type-o from lifting the original?

---

I would fork and make a pull request but I'm lazy.

**Comment by autoric** [comment]
To be honest the uuid generator is a copy/paste from our internal project - I'm not sure what the entire history is. Going through that SO article it looks like there are a lot of solutions with variable performance.  
I could probably revisit, but the uuid generator for scheming is purely for internal registration and doesn't really need to be *globally* unique. It could be an incrementing integer just as easily.

**Comment by autoric** [comment]
Fixed in e4efe228daeb087c5849fa9d375c2dee9da8bbf1
